global:
  scrape_interval: 10s  # a cada 15 segundos vai coletar métricas

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: "prometheus"

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq-exporter:9419']
        labels:
          service: "rabbitmq"
    metrics_path: /metrics
    basic_auth:
      username: admin
      password: admin

  - job_name: 'sonarqube'
    static_configs:
      - targets: ['sonarqube:9000']
        labels:
          service: "sonarqube"
    metrics_path: /api/metrics/search

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: "postgres"